/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LendingCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GRACE_TO_DEFAULT"
      | "PENALTY_BPS_PER_DAY"
      | "TERM"
      | "USDC"
      | "acceptBid"
      | "bids"
      | "cancelBid"
      | "loans"
      | "markDefault"
      | "minimumPayment"
      | "nextBidId"
      | "nextLoanId"
      | "outstanding"
      | "repay"
      | "status"
      | "submitBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidAccepted"
      | "BidCancelled"
      | "BidSubmitted"
      | "Defaulted"
      | "Repaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GRACE_TO_DEFAULT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PENALTY_BPS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "TERM", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "bids", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextBidId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "outstanding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "status",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "GRACE_TO_DEFAULT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PENALTY_BPS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TERM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextBidId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "outstanding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
}

export namespace BidAcceptedEvent {
  export type InputTuple = [
    bidId: BigNumberish,
    loanId: BigNumberish,
    lender: AddressLike
  ];
  export type OutputTuple = [bidId: bigint, loanId: bigint, lender: string];
  export interface OutputObject {
    bidId: bigint;
    loanId: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidCancelledEvent {
  export type InputTuple = [bidId: BigNumberish];
  export type OutputTuple = [bidId: bigint];
  export interface OutputObject {
    bidId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    bidId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    aprBps: BigNumberish,
    recommendedAmount: BigNumberish,
    recommendedApr: BigNumberish
  ];
  export type OutputTuple = [
    bidId: bigint,
    borrower: string,
    amount: bigint,
    aprBps: bigint,
    recommendedAmount: bigint,
    recommendedApr: bigint
  ];
  export interface OutputObject {
    bidId: bigint;
    borrower: string;
    amount: bigint;
    aprBps: bigint;
    recommendedAmount: bigint;
    recommendedApr: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    timestamp: BigNumberish,
    outstanding: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    timestamp: bigint,
    outstanding: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    timestamp: bigint;
    outstanding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    payer: AddressLike,
    amount: BigNumberish,
    newRepaid: BigNumberish,
    outstanding: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    payer: string,
    amount: bigint,
    newRepaid: bigint,
    outstanding: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    payer: string;
    amount: bigint;
    newRepaid: bigint;
    outstanding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingCore extends BaseContract {
  connect(runner?: ContractRunner | null): LendingCore;
  waitForDeployment(): Promise<this>;

  interface: LendingCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GRACE_TO_DEFAULT: TypedContractMethod<[], [bigint], "view">;

  PENALTY_BPS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  TERM: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  acceptBid: TypedContractMethod<[bidId: BigNumberish], [bigint], "nonpayable">;

  bids: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        borrower: string;
        amount: bigint;
        aprBps: bigint;
        recommendedAmount: bigint;
        recommendedAprBps: bigint;
        open: boolean;
      }
    ],
    "view"
  >;

  cancelBid: TypedContractMethod<[bidId: BigNumberish], [void], "nonpayable">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        borrower: string;
        lender: string;
        principal: bigint;
        aprBps: bigint;
        start: bigint;
        due: bigint;
        defaultDate: bigint;
        repaid: bigint;
        settled: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;

  markDefault: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  minimumPayment: TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;

  nextBidId: TypedContractMethod<[], [bigint], "view">;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  outstanding: TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;

  repay: TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  status: TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;

  submitBid: TypedContractMethod<
    [
      amount: BigNumberish,
      aprBps: BigNumberish,
      recommendedAmount: BigNumberish,
      recommendedApr: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GRACE_TO_DEFAULT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PENALTY_BPS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TERM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<[bidId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        borrower: string;
        amount: bigint;
        aprBps: bigint;
        recommendedAmount: bigint;
        recommendedAprBps: bigint;
        open: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBid"
  ): TypedContractMethod<[bidId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        borrower: string;
        lender: string;
        principal: bigint;
        aprBps: bigint;
        start: bigint;
        due: bigint;
        defaultDate: bigint;
        repaid: bigint;
        settled: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDefault"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "minimumPayment"
  ): TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextBidId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "outstanding"
  ): TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [loanId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      aprBps: BigNumberish,
      recommendedAmount: BigNumberish,
      recommendedApr: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "BidAccepted"
  ): TypedContractEvent<
    BidAcceptedEvent.InputTuple,
    BidAcceptedEvent.OutputTuple,
    BidAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "BidCancelled"
  ): TypedContractEvent<
    BidCancelledEvent.InputTuple,
    BidCancelledEvent.OutputTuple,
    BidCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Defaulted"
  ): TypedContractEvent<
    DefaultedEvent.InputTuple,
    DefaultedEvent.OutputTuple,
    DefaultedEvent.OutputObject
  >;
  getEvent(
    key: "Repaid"
  ): TypedContractEvent<
    RepaidEvent.InputTuple,
    RepaidEvent.OutputTuple,
    RepaidEvent.OutputObject
  >;

  filters: {
    "BidAccepted(uint256,uint256,address)": TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;
    BidAccepted: TypedContractEvent<
      BidAcceptedEvent.InputTuple,
      BidAcceptedEvent.OutputTuple,
      BidAcceptedEvent.OutputObject
    >;

    "BidCancelled(uint256)": TypedContractEvent<
      BidCancelledEvent.InputTuple,
      BidCancelledEvent.OutputTuple,
      BidCancelledEvent.OutputObject
    >;
    BidCancelled: TypedContractEvent<
      BidCancelledEvent.InputTuple,
      BidCancelledEvent.OutputTuple,
      BidCancelledEvent.OutputObject
    >;

    "BidSubmitted(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "Defaulted(uint256,uint256,uint256)": TypedContractEvent<
      DefaultedEvent.InputTuple,
      DefaultedEvent.OutputTuple,
      DefaultedEvent.OutputObject
    >;
    Defaulted: TypedContractEvent<
      DefaultedEvent.InputTuple,
      DefaultedEvent.OutputTuple,
      DefaultedEvent.OutputObject
    >;

    "Repaid(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
    Repaid: TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
  };
}
